version: 3.0.{build}
build: off

test_script:
    - cd test\Bandwidth.Net.Test
    - dotnet restore
    - dotnet build
    - cd bin\Debug\net45
    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -target:"%HOMEDRIVE%%HOMEPATH%\.nuget\packages\xunit.runner.console\2.2.0\tools\xunit.console.exe" -targetargs:"Bandwidth.Net.Test.dll -noshadow -parallel none -appveyor" -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Bandwidth*]* -[*Test]*" -searchdirs:"." -register:user' 
    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages\ReportGenerator\2.5.6\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:html -reporttypes:TextSummary'
    - type html\Summary.txt
    - cd ..\..\..\..\..
    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe --opencover -i test\Bandwidth.Net.Test\bin\Debug\net45\coverage.xml --useRelativePaths'

after_test:
    - cd src\Bandwidth.Net
    - deployGHPages.cmd
