version: 3.0.{build}
build: off
environment:  
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
install:  
  # Download .NET Core 2.0
  - ps: $urlCurrent = "https://download.microsoft.com/download/1/B/4/1B4DE605-8378-47A5-B01B-2C79D6C55519/dotnet-sdk-2.0.0-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"  
test_script:
    - cd test\Bandwidth.Net.Test
    - dotnet restore
    - dotnet build
    - cd bin\Debug\net45
    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -target:"%HOMEDRIVE%%HOMEPATH%\.nuget\packages\xunit.runner.console\2.2.0\tools\xunit.console.exe" -targetargs:"Bandwidth.Net.Test.dll -noshadow -parallel none -appveyor" -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Bandwidth*]* -[*Test]*" -searchdirs:"." -register:user' 
    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages\ReportGenerator\2.5.6\tools\ReportGenerator.exe -reports:coverage.xml -targetdir:html -reporttypes:TextSummary'
    - type html\Summary.txt
    - cd ..\..\..\..\..
    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe --opencover -i test\Bandwidth.Net.Test\bin\Debug\net45\coverage.xml --useRelativePaths'

after_test:
    - cd src\Bandwidth.Net
    - deployGHPages.cmd
    - deploy.cmd
